### ISSUE TITLE
Integrate Login with JSFiddle details

### ISSUE THREAD

**Issue by akashRindhe** [akashRindhe/codeForChange#1]

**Comment by akashRindhe** [comment]
Hey @shelviadh, please use the login-service file in the provider folder to create the login function.
Similar to what has been done for events-service

**Comment by r-sudarshan** [comment]
@akashRindhe, A single login page would be simplistic. I believe a separate welcome page is not needed.

**Comment by akashRindhe** [comment]
A welcome page is good user experience, as most apps nowadays have a sort of welcome page where they give you options to login and sign up. Our welcome page currently allows users to login and in the future, a similar sign up functionality can also be introduced.

Nevertheless, we can get feedback from Noel about this and remove it if he thinks otherwise. It is a minimum effort task.

**Comment by shelviadh** [comment]
this issue covers username password authentication - done
