### ISSUE TITLE
Invite others to download/use the app

### ISSUE THREAD

**Issue by bennyirawan** [akashRindhe/codeForChange#18]
Try to support

- SMS (must)
- Whatsapp/Line/WeChat (good to have)
- Facebook (if possible)

**Comment by hari-allamraju** [comment]
ionic-native/social-sharing

**Comment by hari-allamraju** [comment]
Support added to share to twitter, whatsapp, facebook and SMS.
Pending contact seach for SMS if really required - for now this leaves to field empty and user can enter phone number from their contacts

**Comment by hari-allamraju** [comment]
committed and pushed to master
