### ISSUE TITLE
Login error handling not correct

### ISSUE THREAD

**Issue by hari-allamraju** [akashRindhe/codeForChange#21]
At the moment even if I enter an invalid login credential it shows the events page when testing from ionic view and the browser. Need to catch the login error and handle it

**Comment by akashRindhe** [comment]
It's not exactly an error. I had hard-coded it to go through regardless of the details. Once we get the authentication service working, I will include the error part

**Comment by akashRindhe** [comment]
Closing this issue now since it isn't relevant
